echo 'Processing bashrc.sh'

# [TODO VERIFY THAT $HOME IS DEFINED]

# LOAD PATH OF DOTFILES FROM `.dotfiles`.
DOTFILES_PATH="$(cat "$HOME/.dotfiles")"

# SET INITIATOR VARIABLE AND BOOT DOTFILES
DOTFILES_BOOTER='BASHRC'
. "$DOTFILES_PATH/bash/boot.sh"
